**1. What does Pandas stand for?**
<p>-Name derived from “panel data” (or Python Data Analysis) a term for multidimensional structured datasets.

**2. What are the 2 collections used in Pandas?**
<p>-The two collections used in Pandas are Series and Dataframes.

**3. Name 4 things Pandas can do for us.**
<p>-Clean data
<p>-Normalize data
<p>-Data visualizations
<p>-Inspect data

**4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?**
<p>-Include the "inplace=True" statement to permanently sort a df. 

**5. What is a CSV**
<p>-Comma separated value formatted file type.

**6. When cleaning data what values do we not like in our data?**
<p>-Blanks are values that are not desired in one's data therefore the user will have to decide what to do with blanks whether it will be to replace or remove.

In [10]:
#7.Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). 
#You can use the reshape method -- .reshape()

import numpy as np

df = np.arange(12).reshape(2,3,2)
print(df)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [17]:
""" 8. Use NumPy .linspace() to create an array with 6 linearly spaced 
values between 0 and 20
 """
import numpy as np
import copy

df = np.linspace(0,20,num=6)
print(df)


#9. Make a deepcopy of the above array.
df_deepcopy = copy.deepcopy(df)
df_deepcopy

[ 0.  4.  8. 12. 16. 20.]


array([ 0.,  4.,  8., 12., 16., 20.])

In [ ]:
#10 has been removed per TA 5/18/2023.

In [ ]:
#11 Concatenate these 3 arrays into a new array named 'newArray'

import numpy as np

arr1 = np.array([[25, 16]])
arr2 = np.array([[11, 2], [13, 4]])
arr3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arr1,arr2,arr3))
print(newArray)

#12. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print("\nSorted Array\n",sortedArray)

#13. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = np.reshape(sortedArray,newshape=(2,2,3))
print("\nReshaped Array\n",reshapedArray)

#14. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

reshapedArray = np.concatenate(reshapedArray).tolist() #converting ArrayType into a list to allow for unpacking.

group_1, group_2, group_3, group_4 = reshapedArray

print("\nUnpacked Array Items\n")
print(group_1)
print(group_2)
print(group_3)
print(group_4)


In [ ]:
#15. Combine and sort the following arrays into one called 'comboArray'

import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one,two, three), axis=0)
comboArray.sort(axis=0)
print(comboArray)


#16 Complete the following print tasks for the comboArray dataset

#print the 2nd element
print(comboArray[1])

#print all elements from the 3rd element to the last
print(comboArray[2:])

#print all elements from the 4th to the 14th elements
print(comboArray[3:14])

#print the last 6 elements
print(comboArray[-6:])

#print all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[:-10])

#print from #20 every even element to the end
print(comboArray[16::2])

#print from the last element moving forward, every 5th element.
count = 1

for index_pos in comboArray:
    if count % 5 == 0:
        count += 1
        print(index_pos)
    else:
        count +=1

#17, 18, 19 have been removed per TA 5/18/2023.

In [ ]:
#20 Using Series, create a DataFrame that looks like this:

import pandas as pd

data = {
    "Ingredients": ["flour", "milk", "eggs", "spam"],
    "Height": [4,1,2,1],
    "Unit": ["cups", "cup", "large", "can"]
}

df = pd.DataFrame(data)
print(df)

In [ ]:
#21 create a DataFrame named studentData

import pandas as pd

student_data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

df = pd.DataFrame(student_data, columns=["Name", "Height", "Qualification", "Address", "Age", "Pets", "Sport"])

print(student_data)
#22 Add a new column to the student_data df with the following deserts

deserts = ["ice cream", "cashew fudge", "waffels", "carrot halwa"]

df["Desert"] = deserts
print(type(df))

#23 Sort the student_data df in ASC order for columns 'name' and 'address'

df.sort_values(by=['Name', 'Address'],inplace=True,ascending=True)
print(df)


In [166]:
#24 Saving df to a .csv file : Name file cows_and_goats.csv

import numpy as np
import pandas as pd

df = pd.DataFrame({
    'cows': [12,20],
    'goats': [22,19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')


In [168]:
#25a Create a csv file using pandas on vegetables and save it

import numpy as np
import pandas as pd

df_veggie_data = pd.DataFrame({
    'veggie_name': ['cucumber', 'carrot', 'turnip', 'onion', 'squash'],
    'on_hand_qty': [65,120,88,12,5]
})

df_veggie_data.to_csv('veggie_inventory.csv')


In [170]:
#25b update your veggie_inventory csv file using pandas and save as another name

import numpy as np
import pandas as pd

df_veggie_data_v2 = pd.DataFrame({
    'veggie_name': ['cucumber', 'carrot', 'turnip', 'onion', 'squash', 'mint', 'green onion', 'green pepper'],
    'on_hand_qty': [65,100,88,65,445,52,45,10]
})

df_veggie_data_v2.to_csv('veggie_inventory_v2.csv')